package com.model;

// default package 
// Generated Mar 12, 2016 3:09:14 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * RoomType generated by hbm2java
 */
@Entity
@Table(name = "UPLOAD2", schema = "sl_learn_zk_upload_1")
public class Upload2 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int uploadID;
	private String fileName;
	private int fileSize;
	private int lastUpload;
	private int uploadStatus;
	private String logPath;

	/**
	 * 
	 */
	public Upload2() {
		// TODO Auto-generated constructor stub
	}

	public Upload2(int uploadID, String fileName, int fileSize, int lastUpload, int uploadStatus, String logPath) {
		super();
		this.uploadID = uploadID;
		this.fileName = fileName;
		this.fileSize = fileSize;
		this.lastUpload = lastUpload;
		this.uploadStatus = uploadStatus;
		this.logPath = logPath;
	}

	@Id
	@SequenceGenerator(name = "SEQ_UPLOAD2", sequenceName = "SEQ_UPLOAD2")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQ_UPLOAD2")
	@Column(name = "upload_id", unique = true, nullable = false)
	public int getUploadID() {
		return uploadID;
	}

	public void setUploadID(int uploadID) {
		this.uploadID = uploadID;
	}

	@Column(name = "file_name", length = 100)
	public String getFileName() {
		return fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "file_size")
	public int getFileSize() {
		return fileSize;
	}

	public void setFileSize(int fileSize) {
		this.fileSize = fileSize;
	}

	@Column(name = "last_upload")
	public int getLastUpload() {
		return lastUpload;
	}

	public void setLastUpload(int lastUpload) {
		this.lastUpload = lastUpload;
	}

	@Column(name = "upload_status")
	public int getUploadStatus() {
		return uploadStatus;
	}

	public void setUploadStatus(int uploadStatus) {
		this.uploadStatus = uploadStatus;
	}

	@Column(name = "log_path")
	public String getLogPath() {
		return logPath;
	}

	public void setLogPath(String logPath) {
		this.logPath = logPath;
	}

}
